[========] TestException
test_exception.cpp(28): 
what
[ FAILED ] test_out_of_bound
[=   0% =] 
0 / 1 test cases passed. 

[=   0% =] 
0 / 1 test cases passed. 
